services:
  # ==========================================
  # СЕРВИС 1: База данных PostgreSQL
  # ==========================================
  db:
    image: postgres:16
    container_name: splitbot_postgres
    environment:
      POSTGRES_DB: splitbot_db
      POSTGRES_USER: bot_user
      POSTGRES_PASSWORD: secretpassword123
    ports:
      - "5432:5432"
    volumes:

      # Прокидываем твой файл schema.sql в специальную папку инициализации Postgres.
      # При первом запуске база сама выполнит этот скрипт и создаст все таблицы!
      - ./SplitTGBot/schema.sql:/docker-entrypoint-initdb.d/init.sql
      # Сохраняем данные на диске, чтобы при перезапуске контейнера записи не удалялись
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bot_user -d splitbot_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # ==========================================
  # СЕРВИС 2: Твой Telegram-бот на C#
  # ==========================================
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: splitbot_app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_CONNECTION: "Host=db;Port=5432;Database=splitbot_db;Username=bot_user;Password=secretpassword123"
      # Токен берется из локального файла .env (который скрыт от git!)
      BOT_TOKEN: ${BOT_TOKEN}

volumes:
  pg_data:
